# SPDX-FileCopyrightText: 2023 Double Open Oy
#
# SPDX-License-Identifier: MIT

excludes:
  scopes:
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  paths:
  - pattern: ".reuse/dep5"
    reason: "OTHER"
    comment: "This file declares license information for the REUSE tool."
  - pattern: "LICENSES/*"
    reason: "OTHER"
    comment: "This directory contains license files for the REUSE tool."
  - pattern: "apps/curation_front_end/.next/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory is produced by npm build on NextJS projects."
  - pattern: "apps/curation_front_end/src/testData/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for matchers."
  - pattern: "packages/database/src/test_data/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for the database."

license_choices:
  package_license_choices:
  - package_id: "NPM::fraction.js:4.3.7"
    license_choices:
    - given: GPL-2.0-only OR MIT
      choice: MIT
  - package_id: "NPM::lodash:4.17.21"
    license_choices:
    - given: MIT OR BSD-3-Clause OR GPL-2.0-only
      choice: MIT
  - package_id: "NPM::lodash.defaults:4.2.0"
    license_choices:
    - given: MIT OR BSD-3-Clause OR GPL-2.0-only
      choice: MIT
  - package_id: "NPM::lodash.isarguments:3.1.0"
    license_choices:
    - given: MIT OR BSD-3-Clause OR GPL-2.0-only
      choice: MIT
  - package_id: "NPM::type-fest:0.6.0"
    license_choices:
    - given: CC0-1.0 OR MIT
      choice: MIT
  - package_id: "NPM::type-fest:0.8.1"
    license_choices:
    - given: CC0-1.0 OR MIT
      choice: MIT
  - package_id: "NPM::type-fest:0.16.0"
    license_choices:
    - given: CC0-1.0 OR MIT
      choice: MIT
  - package_id: "NPM::type-fest:0.21.3"
    license_choices:
    - given: CC0-1.0 OR MIT
      choice: MIT
