# SPDX-FileCopyrightText: 2023 Double Open Oy
#
# SPDX-License-Identifier: MIT

excludes:
  scopes:
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  paths:
  - pattern: ".reuse/dep5"
    reason: "OTHER"
    comment: "This file declares license information for the REUSE tool."
  - pattern: "LICENSES/*"
    reason: "OTHER"
    comment: "This directory contains license files for the REUSE tool."
  - pattern: "apps/clearance_ui/.next/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory is produced by npm build on NextJS projects."
  - pattern: "apps/clearance_ui/tests/**"
    reason: "TEST_OF"
    comment: "This directory only contains tests."
  - pattern: "apps/clearance_ui/src/testData/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for matchers."
  - pattern: "packages/database/src/test_data/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for the database."
  - pattern: "packages/spdx-validation/tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests for SPDX validation."

license_choices:
  repository_license_choices:
  - given: CC0-1.0 OR MIT
    choice: MIT
  - given: GPL-2.0-only OR MIT
    choice: MIT
  - given: MIT OR BSD-3-Clause OR GPL-2.0-only
    choice: MIT

curations:
  license_findings:
  - path: "README.md"
    detected_license: "MIT AND LicenseRef-scancode-free-unknown"
    reason: "INCORRECT"
    comment: "Incorrect scanner match."
    concluded_license: "MIT"
  - path: "packages/spdx-validation/README.md"
    detected_license: "MIT AND (MIT AND JSON) AND (BSD-2-Clause AND GPL-2.0-only WITH GCC-exception-2.0 AND GPL-2.0-only WITH GCC-exception-2.0 AND CC-BY-3.0 AND MIT)"
    reason: "INCORRECT"
    comment: "Incorrect scanner matches coming from SPDX license parsing examples in README."
    concluded_license: "MIT"