# SPDX-FileCopyrightText: 2023 Double Open Oy
#
# SPDX-License-Identifier: MIT

excludes:
  scopes:
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  paths:
  - pattern: ".reuse/dep5"
    reason: "OTHER"
    comment: "This file declares license information for the REUSE tool."
  - pattern: "LICENSES/*"
    reason: "OTHER"
    comment: "This directory contains license files for the REUSE tool."
  - pattern: "apps/curation_front_end/.next/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory is produced by npm build on NextJS projects."
  - pattern: "apps/curation_front_end/src/testData/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for matchers."
  - pattern: "packages/database/src/test_data/**"
    reason: "TEST_OF"
    comment: "This directory only contains test data for the database."

license_choices:
  repository_license_choices:
  - given: CC0-1.0 OR MIT
    choice: MIT
  - given: GPL-2.0-only OR MIT
    choice: MIT
  - given: MIT OR BSD-3-Clause OR GPL-2.0-only
    choice: MIT
