# SPDX-FileCopyrightText: 2025 Double Open Oy
# 
# SPDX-License-Identifier: MIT

FROM hashicorp/terraform:1.6

# These are needed for running the role mapper patching script
RUN apk add --no-cache curl jq
